version: "3.7"

services:
  app:
    image: castopod/app:latest
    container_name: "castopod-app"
    volumes:
      - castopod-media:/opt/castopod/public/media
      - ./ila_app:/opt/castopod/themes/cp_app
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CP_BASEURL: "https://podcast.leftarchive.ie"
      CP_ANALYTICS_SALT: ${CP_ANALYTICS_SALT}
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: redis
      CI_ENVIRONMENT: development
    networks:
      - castopod-app
      - castopod-db
    restart: unless-stopped
    depends_on:
      - mariadb

  web-server:
    image: castopod/web-server:latest
    container_name: "castopod-web-server"
    volumes:
      - castopod-media:/var/www/html/media
    networks:
      - castopod-app
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - app

  mariadb:
    image: mariadb:10.5
    container_name: "castopod-mariadb"
    networks:
      - castopod-db
    volumes:
      - castopod-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  redis:
   image: redis:7.0-alpine
   container_name: "castopod-redis"
   volumes:
     - castopod-cache:/data
   networks:
     - castopod-app

#  video-clipper:
#    image: castopod/video-clipper:latest
#    container_name: "castopod-video-clipper"
#    volumes:
#      - castopod-media:/opt/castopod/public/media
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    networks:
#      - castopod-db
#    restart: unless-stopped

volumes:
  castopod-media:
  castopod-db:
  castopod-cache:
  castopod-theme:
  
networks:
  castopod-app:
  castopod-db: 
