version: "3.7"

services:
  app:
    image: castopod/app:latest
    container_name: "castopod-app"
    volumes:
      - castopod-media:/var/www/castopod/public/media
      - ./ila-media:/var/www/castopod/public/media/ila
      - ./en/Podcast.php:/var/www/castopod/app/Language/en/Podcast.php
      - ./en/Episode.php:/var/www/castopod/app/Language/en/Episode.php
      - ./cp_app/embed.php:/var/www/castopod/themes/cp_app/embed.php
      - ./cp_app/pages/_layout.php:/var/www/castopod/themes/cp_app/pages/_layout.php
      - ./cp_app/episode/_layout.php:/var/www/castopod/themes/cp_app/episode/_layout.php
      - ./cp_app/podcast/_layout.php:/var/www/castopod/themes/cp_app/podcast/_layout.php
      - ./cp_app/podcast/_partials/sidebar.php:/var/www/castopod/themes/cp_app/podcast/_partials/sidebar.php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CP_BASEURL: ${CP_BASEURL}
      CP_MEDIA_BASEURL: ${CP_MEDIA_BASEURL}
      CP_ANALYTICS_SALT: ${CP_ANALYTICS_SALT}
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: redis
      CP_EMAIL_SMTP_HOST: ${CP_EMAIL_SMTP_HOST}
      CP_EMAIL_FROM: ${CP_EMAIL_FROM}
      CP_EMAIL_SMTP_USERNAME: ${CP_EMAIL_SMTP_USERNAME}
      CP_EMAIL_SMTP_PASSWORD: ${CP_EMAIL_SMTP_PASSWORD}
      CP_EMAIL_SMTP_PORT: ${CP_EMAIL_SMTP_PORT}
      CP_REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - castopod-app
      - castopod-db
    restart: unless-stopped
    depends_on:
      - mariadb

  web-server:
    image: castopod/web-server:latest
    container_name: "castopod-web-server"
    volumes:
      - castopod-media:/var/www/html/media
      - ./ila-media:/var/www/html/media/ila
    networks:
      - castopod-app
    ports:
      - 127.0.0.1:${PORT}:80
    restart: unless-stopped
    depends_on:
      - app

  mariadb:
    image: mariadb:10.11
    container_name: "castopod-mariadb"
    networks:
      - castopod-db
    volumes:
      - castopod-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  redis:
   image: redis:7.0-alpine
   container_name: "castopod-redis"
   volumes:
     - castopod-cache:/data
   networks:
     - castopod-app
   command: >
       --requirepass ${REDIS_PASSWORD}

volumes:
  castopod-media:
    name: "castopod_castopod-media"
    external: true
  castopod-db:
    name: "castopod_castopod-db"
    external: true
  castopod-cache:
  
networks:
  castopod-app:
  castopod-db: 
